server:
  port: 8382
  http2:
    enabled: true



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HibernatePractic
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  security:
    user:
      password: password

jpa:
  properties:
    hibernate:
      default_schema: data_jpa
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

logging:
    level:
      root: INFO
      org.springframework.jdbc.core: TRACE
      org.springframework.security: TRACE

jwt:
  access-token-key: '{"kty":"oct","k":"404491d134b23069cd800106d3e2edd63996def57f8f1530e4e7bc8dbdf80fb9"}'
  refresh-token-key: '{"kty":"oct","k":"404491d134b23069cd800106d3e2edd63996def57f8f1530e4e7bc8dbdf80fb9"}'
  request-path: "/jwt/tokens"




